services:
  db:
    image: postgres:16
    container_name: nexora_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: nexora_admin
      POSTGRES_PASSWORD: nexora_password
      POSTGRES_DB: nexora
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
